"""
Django settings for multiprojector project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from django.utils import encoding
from pathlib import Path
from dotenv import load_dotenv

# loading parameters
load_dotenv(override=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = encoding.force_str(os.getenv("django-secret"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv("debug").lower() == "true")

ALLOWED_HOSTS = os.getenv("allowed-host").split(",")
# important for proxy forwarding
CSRF_TRUSTED_ORIGINS = os.getenv(
    "csrf-trusted-hosts").split(",") if os.getenv("csrf-trusted-hosts") != "" else []

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'streaming',
]

if os.getenv("admin-page-enabled").lower() == "true":
    INSTALLED_APPS.append('django.contrib.admin')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'multiprojector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend/dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'multiprojector.wsgi.application'
ASGI_APPLICATION = 'multiprojector.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_TYPE = os.getenv("db-type")
if DB_TYPE == "postgres":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("db-name", "cgnsystem"),
            'USER': os.getenv("db-user"),
            'PASSWORD': os.getenv("db-password"),
            'HOST': os.getenv("db-host", "localhost"),
            'PORT': os.getenv("db-port", "5432")
        }
    }
elif DB_TYPE in ["mariadb", "mysql"]:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv("db-name", "cgnsystem"),
            'USER': os.getenv("db-user"),
            'PASSWORD': os.getenv("db-password"),
            'HOST': os.getenv("db-host", "localhost"),
            'PORT': os.getenv("db-port", "3306")
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'TEST': {
                'NAME': os.getenv("db-name", "cgnsystem"),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'assets/'

STATIC_ROOT = BASE_DIR / "frontend/whitenoise"

STATICFILES_DIRS = [
    BASE_DIR / "frontend/dist/assets"
]

if os.getenv("static-host-redirect") is not None and os.getenv("static-host-redirect").lower() != "":
    REDIRECT_STATIC_URL = 'src/'
    TEMPLATES[0]['DIRS'] = [BASE_DIR / 'frontend']
else:
    MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
