# Generated by Django 6.0.1 on 2026-02-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsession',
            name='resolution_x',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='streamingsession',
            name='resolution_y',
            field=models.IntegerField(default=1920),
        ),
    ]
